config/routes.rb
Bandrockr::Application.routes.draw do
  resources :gigs

  resources :photos

  resources :band_profiles

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/band_profile.rb
class BandProfile < ActiveRecord::Base
  has_many :gigs
  has_many :photos
end

app/controllers/band_profiles_controller.rb
class BandProfilesController < ApplicationController
  before_action :set_band_profile, only: [:show, :edit, :update, :destroy]

  # GET /band_profiles
  # GET /band_profiles.json
  def index
    @band_profiles = BandProfile.all
  end

  # GET /band_profiles/1
  # GET /band_profiles/1.json
  def show
  end

  # GET /band_profiles/new
  def new
    @band_profile = BandProfile.new
  end

  # GET /band_profiles/1/edit
  def edit
  end

  # POST /band_profiles
  # POST /band_profiles.json
  def create
    @band_profile = BandProfile.new(band_profile_params)

    respond_to do |format|
      if @band_profile.save
        format.html { redirect_to @band_profile, notice: 'Band profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @band_profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @band_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /band_profiles/1
  # PATCH/PUT /band_profiles/1.json
  def update
    respond_to do |format|
      if @band_profile.update(band_profile_params)
        format.html { redirect_to @band_profile, notice: 'Band profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @band_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /band_profiles/1
  # DELETE /band_profiles/1.json
  def destroy
    @band_profile.destroy
    respond_to do |format|
      format.html { redirect_to band_profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_band_profile
      @band_profile = BandProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def band_profile_params
      params.require(:band_profile).permit(:name, :info, :facebook, :twitter, :soundcloud)
    end
end

app/helpers/band_profiles_helper.rb
module BandProfilesHelper
end

app/views/band_profiles/_form.html.erb
<%= simple_form_for(@band_profile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :info %>
    <%= f.input :facebook %>
    <%= f.input :twitter %>
    <%= f.input :soundcloud %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/band_profiles/edit.html.erb
<h1>Editing band_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @band_profile %> |
<%= link_to 'Back', band_profiles_path %>

app/views/band_profiles/index.html.erb
<h1>Listing band_profiles</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th>Info</th>
      <th>Facebook</th>
      <th>Twitter</th>
      <th>Soundcloud</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @band_profiles.each do |band_profile| %>
      <tr>
        <td><%= band_profile.name %></td>
        <td><%= band_profile.info %></td>
        <td><%= band_profile.facebook %></td>
        <td><%= band_profile.twitter %></td>
        <td><%= band_profile.soundcloud %></td>
        <td><%= link_to 'Show', band_profile %></td>
        <td><%= link_to 'Edit', edit_band_profile_path(band_profile) %></td>
        <td><%= link_to 'Destroy', band_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Band profile', new_band_profile_path, class: 'btn btn-success btn-large'%>

app/views/band_profiles/new.html.erb
<h1>New band_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', band_profiles_path %>

app/views/band_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @band_profile.name %>
</p>

<p>
  <strong>Info:</strong>
  <%= @band_profile.info %>
</p>

<p>
  <strong>Facebook:</strong>
  <%= @band_profile.facebook %>
</p>

<p>
  <strong>Twitter:</strong>
  <%= @band_profile.twitter %>
</p>

<p>
  <strong>Soundcloud:</strong>
  <%= @band_profile.soundcloud %>
</p>

<hr>
<hr2><%= @band_profile.name %>'s Gigs </h2>
<% @band_profile.gigs.each do |gig| %>
    <p><%= gig.title %></p>
    <p><%= gig.date %></p>
    <hr>
<% end%> 

<% if @band_profile.photos%>
<%= image_tag @band_profile.photos.first.image, class: 'img-rounded' %>
<% end %>
    
<%= link_to 'Edit', edit_band_profile_path(@band_profile) %> |
<%= link_to 'Back', band_profiles_path %>