config/routes.rb
Bandrockr::Application.routes.draw do
  resources :gigs

  resources :photos

  resources :band_profiles

  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
end

app/models/gig.rb
class Gig < ActiveRecord::Base
  belongs_to :band_profile
end

app/controllers/gigs_controller.rb
class GigsController < ApplicationController
  before_action :set_gig, only: [:show, :edit, :update, :destroy]

  # GET /gigs
  # GET /gigs.json
  def index
    @gigs = Gig.all
  end

  # GET /gigs/1
  # GET /gigs/1.json
  def show
  end

  # GET /gigs/new
  def new
    @gig = Gig.new
  end

  # GET /gigs/1/edit
  def edit
  end

  # POST /gigs
  # POST /gigs.json
  def create
    @gig = Gig.new(gig_params)

    respond_to do |format|
      if @gig.save
        format.html { redirect_to @gig, notice: 'Gig was successfully created.' }
        format.json { render action: 'show', status: :created, location: @gig }
      else
        format.html { render action: 'new' }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gigs/1
  # PATCH/PUT /gigs/1.json
  def update
    respond_to do |format|
      if @gig.update(gig_params)
        format.html { redirect_to @gig, notice: 'Gig was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @gig.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gigs/1
  # DELETE /gigs/1.json
  def destroy
    @gig.destroy
    respond_to do |format|
      format.html { redirect_to gigs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gig
      @gig = Gig.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gig_params
      params.require(:gig).permit(:title, :date, :start_time, :finish_time, :location, :street_address, :suburb, :tickets_url, :band_profile_id)
    end
end

app/helpers/gigs_helper.rb
module GigsHelper
end

app/views/gigs/_form.html.erb
<%= simple_form_for(@gig) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :date %>
    <%= f.input :start_time %>
    <%= f.input :finish_time %>
    <%= f.input :location %>
    <%= f.input :street_address %>
    <%= f.input :suburb %>
    <%= f.input :tickets_url %>
    <%= f.association :band_profile %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gigs/edit.html.erb
<h1>Editing gig</h1>

<%= render 'form' %>

<%= link_to 'Show', @gig %> |
<%= link_to 'Back', gigs_path %>

app/views/gigs/index.html.erb
<h1>Listing gigs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Date</th>
      <th>Start time</th>
      <th>Finish time</th>
      <th>Location</th>
      <th>Street address</th>
      <th>Suburb</th>
      <th>Tickets url</th>
      <th>Band profile</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @gigs.each do |gig| %>
      <tr>
        <td><%= gig.title %></td>
        <td><%= gig.date %></td>
        <td><%= gig.start_time %></td>
        <td><%= gig.finish_time %></td>
        <td><%= gig.location %></td>
        <td><%= gig.street_address %></td>
        <td><%= gig.suburb %></td>
        <td><%= gig.tickets_url %></td>
        <td><%= gig.band_profile.name %></td>
        <td><%= link_to 'Show', gig %></td>
        <td><%= link_to 'Edit', edit_gig_path(gig) %></td>
        <td><%= link_to 'Destroy', gig, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gig', new_gig_path %>

app/views/gigs/new.html.erb
<h1>New gig</h1>

<%= render 'form' %>

<%= link_to 'Back', gigs_path %>

app/views/gigs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @gig.title %>
</p>

<p>
  <strong>Date:</strong>
  <%= @gig.date %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @gig.start_time %>
</p>

<p>
  <strong>Finish time:</strong>
  <%= @gig.finish_time %>
</p>

<p>
  <strong>Location:</strong>
  <%= @gig.location %>
</p>

<p>
  <strong>Street address:</strong>
  <%= @gig.street_address %>
</p>

<p>
  <strong>Suburb:</strong>
  <%= @gig.suburb %>
</p>

<p>
  <strong>Tickets url:</strong>
  <%= @gig.tickets_url %>
</p>

<p>
  <strong>Band profile:</strong>
  <%= @gig.band_profile.name %>
</p>

<%= link_to 'Edit', edit_gig_path(@gig) %> |
<%= link_to 'Back', gigs_path %>